### PR TITLE
Added the ability to specify a timeout in order to terminate during hangups.

### PR DESCRIPTION
**Pull request by arizvisa**
This adds a timeout parameter (`-w`) by implementing a check called `CheckRunningTimeout`. The timeout lets someone specify a number of seconds before terminating the browser. Pretty basic really.

### CODE REVIEW

**Comment by tysmith** [comment]
Hi @arizvisa, thanks for the PR. Before we can accept any new code it must be covered by a test.

Out of curiosity what is your use case for FFPuppet? Is there a reason to not use `wait()` instead?

**Comment by arizvisa** [comment]
Ahh sorry about that. Didn't realize that there was tests for the checks. I'll write one up in a bit.

I'm literally just running it to test an add-on at the commandline, so that if things stall for some amount of time, the `is_healthy` loop has a way to exit. Something like the following (with the -w parameter from this PR) will visit the url for 30 seconds and then terminate.
`$ python -m ffpuppet -w 30 -u url /path/to/binary`

`wait()`? I guess I didn't catch that.. It looked like the loop in main.py was only calling `is_healthy()` which would run the checks at an interval, and so I didn't see any immediate way to exit that loop short of the tests in the `is_healthy()` implementation. Would it be better to replace that loop with a call to `wait()` so that it'd terminate on either a crash report or the timeout specified at the commandline?

**Comment by arizvisa** [comment]
Did you want me to write this? I didn't get any reasponses to my questions so I left it hanging.

**Comment by tysmith** [comment]
I plan to remove all checks from FFPuppet in the future once they are implemented in [Grizzly](//github.com/MozillaSecurity/grizzly). The timeout functionality does exist in Grizzly. 

The cli only existing for testing purposes and I'd really like to slim down this project as much as possible.

I don't know your specific use case but maybe Grizzly can help.

**Comment by arizvisa** [comment]
ok, tru. yea, that was 4 years ago so i'm not using it anymore hence was just offering to contribute if you wanted me to. if it's irrelevant now, then no worries.

**Pull request closed without merging**
