### PR TITLE
Finish typing support.

### PR DESCRIPTION
**Pull request by jschwartzentruber**
This finishes the work by @nth10sd in #115 . Much of the nicer syntax depends on \_\_future\_\_ annotations which has [other caveats](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#future-annotations), so I've backported this to 3.6 for now.

This also enables mypy in pre-commit, enables Python 3.10 CI, and enables lint across all Python versions in CI.

Supersedes #115.

### CODE REVIEW

**Comment by nth10sd** [comment]
In a new fresh Python 3.6 venv on rev 238464c, there still are the following errors:

```
$ mypy .
ffpuppet/test_sanitizer_util.py:15: error: Untyped decorator makes function "test_sanitizer_options_01" untyped  [misc]
ffpuppet/test_minidump_parser.py:165: error: Untyped decorator makes function "test_minidump_parser_06" untyped  [misc]
ffpuppet/test_ffpuppet.py:88: error: Untyped decorator makes function "test_ffpuppet_00" untyped  [misc]
ffpuppet/test_main.py:17: error: Untyped decorator makes function "test_main_01" untyped  [misc]
Found 4 errors in 4 files (checked 21 source files)
```

**Comment by jschwartzentruber** [comment]
> In a new fresh Python 3.6 venv on rev [238464c](https://github.com/MozillaSecurity/ffpuppet/commit/238464cccafc535d5c59a81e1707219b276efebe), there still are the following errors:
> 
> ```
> $ mypy .
> ffpuppet/test_sanitizer_util.py:15: error: Untyped decorator makes function "test_sanitizer_options_01" untyped  [misc]
> ffpuppet/test_minidump_parser.py:165: error: Untyped decorator makes function "test_minidump_parser_06" untyped  [misc]
> ffpuppet/test_ffpuppet.py:88: error: Untyped decorator makes function "test_ffpuppet_00" untyped  [misc]
> ffpuppet/test_main.py:17: error: Untyped decorator makes function "test_main_01" untyped  [misc]
> Found 4 errors in 4 files (checked 21 source files)
> ```

Yes, that's because of missing annotations for pytest fixtures when pytest isn't installed. Using tox or pre-commit will install pytest to avoid these errors.

**Comment by nth10sd** [comment]
Yes, you're right!

**Review by tysmith — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
